### ISSUE TITLE
Invalid TOML file /home/xxxx/pyproject.toml: Empty key at line 8 col 0

### ISSUE THREAD

**Issue by jmodena** [ckaytev/tgisper#1]
When "poetry install" say: "Invalid TOML file /home/xxxx/pyproject.toml: Empty key at line 8 col 0"

**Comment by ckaytev** [comment]
What OS are you using? For Windows and Debian 11 works without errors

**Comment by ckaytev** [comment]
> When "poetry install" say: "Invalid TOML file /home/xxxx/pyproject.toml: Empty key at line 8 col 0"

What OS are you using? For Windows and Debian 11 works without errors
